### ISSUE TITLE
 undefined method `to_past_tense' for "update":String 

### ISSUE THREAD

**Issue by naveed-ahmad** [parolkar/pfeed#5]
i am following all steps in https://github.com/parolkar/pfeed#readme
in console when i tries u=User.new i got error undefined method `to_past_tense' for "update":String

from /home/naveed/7ValsDevelopement/pFeedExampleApp/vendor/plugins/pfeed/lib/pfeed_utils.rb:15:in `attempt_pass_tense'
    from /home/naveed/7ValsDevelopement/pFeedExampleApp/vendor/plugins/pfeed/lib/pfeed.rb:40:in`emits_pfeeds'
    from /home/naveed/7ValsDevelopement/pFeedExampleApp/vendor/plugins/pfeed/lib/pfeed.rb:29:in `each'
    from /home/naveed/7ValsDevelopement/pFeedExampleApp/vendor/plugins/pfeed/lib/pfeed.rb:29:in`emits_pfeeds'
    from /home/naveed/7ValsDevelopement/pFeedExampleApp/app/models/user.rb:17

i am in rails 3.0.4.what is the issue??

**Comment by naveed-ahmad** [comment]
ok i have reinstall inflectionist plugin and issue is resolved
